public enum Metric {
    TOTAL_IMPRESSIONS,
    TOTAL_IMPRESSION_COST,
    TOTAL_CLICKS,
    TOTAL_CLICK_COST,
    TOTAL_COST,
    TOTAL_CONVERSIONS,
    CONVERSION_RATE,
    BOUNCES,
    BOUNCE_RATE,
    TOTAL_UNIQUES,
    CLICK_THROUGH_RATE,
    COST_PER_AQUISITION,
    COST_PER_CLICK,
    COST_PER_1000_IMPRESSIONS
}