public enum Metric {
    TOTAL_IMPRESSIONS,
    TOTAL_IMPRESSION_COST,
    TOTAL_CLICKS,
    TOTAL_CLICK_COST,
    TOTAL_COST,
    TOTAL_CONVERSIONS,
    CONVERSION_RATE,
    BOUNCES,
    BOUNCE_RATE,
    TOTAL_UNIQUES,
    CTR,
    CPA,
    CPC,
    CPM
}